<?php

namespace Database\Seeders;

use \Illuminate\Support\Str;
use App\Models\Letter;
use Illuminate\Database\Seeder;

class LetterSeeder extends Seeder
{

    public function run(): void
    {
        $letters = [
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Berita acara serah terima tanggung jawab',
                'slug' => 'berita-acara-serah-terima-tanggung-jawab',
                'description' => 'Surat pernyataan tanggung jawab mutlak',
                'price' => 15000,
                'category' => "formal",
                'file_path' => null,
            ],
        ];

        foreach ($letters as $letter) {
            Letter::create($letter);
        }
    }
}
